### ISSUE TITLE
Implement basic movement on a level

### ISSUE THREAD

**Issue by alexesmet** [Graph-Donte-Crypto/ProjectSoldering#1]
- [x] Create a floor that Player can stand on
- [x] Implement physics so that Player doesn't fall through the floor
- [x] Implement WASD movement

### Out of scope
- Textures
- Inertia or slippery floor

**Comment by Graph-Donte-Crypto** [comment]
![Image](https://github.com/Graph-Donte-Crypto/ProjectSoldering/assets/38752574/5cc853f8-f194-4269-92f4-9042db7ad924)

**Comment by alexesmet** [comment]
![Image](https://github.com/Graph-Donte-Crypto/ProjectSoldering/assets/36900282/79d34dd0-6b79-4507-9eac-fe6b26c54809)
