### ISSUE TITLE
Add in-air horizontal inertia that can be slightly controlled (incl. dash)

### ISSUE THREAD

**Issue by alexesmet** [Graph-Donte-Crypto/ProjectSoldering#13]
- Let games like DRG and Warframe inspire you
- When dashing, I would also like to see a softer transition from dash to flying state

**Comment by Graph-Donte-Crypto** [comment]
![Image](https://github.com/Graph-Donte-Crypto/ProjectSoldering/assets/38752574/aadc3ff8-5e9f-42cc-9176-ffdc4962fbf6)

@alexesmet 
I don't understand what you want
But now you can feel weight
