### ISSUE TITLE
Dropped item entity

### ISSUE THREAD

**Issue by alexesmet** [Graph-Donte-Crypto/ProjectSoldering#5]
- [x] Create an entity of an item
- [ ] ~~Item must be affected by gravity and physics~~ *(temporary software limitations)*
- [x] Item must be sucked into the Player when nearby and disappear

**Comment by Graph-Donte-Crypto** [comment]
![Image](https://github.com/Graph-Donte-Crypto/ProjectSoldering/assets/38752574/d3bbb973-6b82-4384-bbe4-42c7e5295d78)

@alexesmet
